// <copyright file="IMultiStepSpawner.cs" company="Audino">
// Copyright (c) Audino
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

using System;
using System.Collections.Generic;

namespace RogueElements
{
    /// <summary>
    /// Provides a non-generic interface for multi-step spawners that select from multiple spawner options.
    /// </summary>
    /// <seealso cref="MultiStepSpawner{TGenContext, TSpawnable}"/>
    public interface IMultiStepSpawner
    {
        /// <summary>
        /// Gets or sets the picker that selects which spawners to use.
        /// </summary>
        IMultiRandPicker Picker { get; set; }
    }

    /// <summary>
    /// Randomly chooses an IStepSpawner from a spawner of spawners, then generates the objects from the chosen IStepSpawner.
    /// </summary>
    /// <typeparam name="TGenContext">The generation context type used to inform spawn generation.</typeparam>
    /// <typeparam name="TSpawnable">The type of spawnable entity to generate.</typeparam>
    [Serializable]
    public class MultiStepSpawner<TGenContext, TSpawnable> : IStepSpawner<TGenContext, TSpawnable>, IMultiStepSpawner
        where TGenContext : IGenContext
        where TSpawnable : ISpawnable
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultiStepSpawner{TGenContext, TSpawnable}"/> class.
        /// </summary>
        public MultiStepSpawner()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiStepSpawner{TGenContext, TSpawnable}"/> class with the specified picker.
        /// </summary>
        /// <param name="picker">The picker that selects which spawners to use.</param>
        public MultiStepSpawner(IMultiRandPicker<IStepSpawner<TGenContext, TSpawnable>> picker)
        {
            this.Picker = picker;
        }

        /// <summary>
        /// The spawner of spawners.
        /// </summary>
        public IMultiRandPicker<IStepSpawner<TGenContext, TSpawnable>> Picker { get; set; }

        /// <inheritdoc/>
        IMultiRandPicker IMultiStepSpawner.Picker
        {
            get { return this.Picker; }
            set { this.Picker = (IMultiRandPicker<IStepSpawner<TGenContext, TSpawnable>>)value; }
        }

        /// <summary>
        /// Generates spawns by randomly selecting spawners from the picker and aggregating their results.
        /// </summary>
        /// <param name="map">The generation context used to inform spawn generation.</param>
        /// <returns>A list of spawnable entities generated by the selected spawners.</returns>
        public List<TSpawnable> GetSpawns(TGenContext map)
        {
            if (this.Picker is null)
                return new List<TSpawnable>();
            IMultiRandPicker<IStepSpawner<TGenContext, TSpawnable>> picker = this.Picker;
            if (picker.ChangesState)
                picker = picker.CopyState();
            List<IStepSpawner<TGenContext, TSpawnable>> resultPickers = picker.Roll(map.Rand);
            List<TSpawnable> copyResults = new List<TSpawnable>();
            foreach (IStepSpawner<TGenContext, TSpawnable> resultPicker in resultPickers)
            {
                List<TSpawnable> results = resultPicker.GetSpawns(map);
                foreach (TSpawnable result in results)
                    copyResults.Add((TSpawnable)result.Copy());
            }

            return copyResults;
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return string.Format("{0}: {1}", this.GetType().GetFormattedTypeName(), this.Picker.ToString());
        }
    }
}
